"""CONTRACT_v1 定義的所有固定代碼。不使用 3.11+ 語法（用 str, Enum，不用 StrEnum）。"""

from enum import Enum

SCHEMA_VERSION = "rag-v1"


class IntentTag(str, Enum):
    GENERAL_EDUCATION = "GENERAL_EDUCATION"
    SYMPTOM_INFORMATION = "SYMPTOM_INFORMATION"
    DIAGNOSIS_REQUEST = "DIAGNOSIS_REQUEST"
    GENERAL_MEDICATION_INFORMATION = "GENERAL_MEDICATION_INFORMATION"
    MEDICATION_CHANGE_REQUEST = "MEDICATION_CHANGE_REQUEST"
    NON_MEDICAL = "NON_MEDICAL"


class RiskFlag(str, Enum):
    POSSIBLE_EMERGENCY = "POSSIBLE_EMERGENCY"
    MENTAL_HEALTH_CRISIS = "MENTAL_HEALTH_CRISIS"
    PERSONALIZED_MEDICATION = "PERSONALIZED_MEDICATION"
    HIGH_RISK_NOT_EXCLUDED = "HIGH_RISK_NOT_EXCLUDED"
    PROMPT_INJECTION_SUSPECTED = "PROMPT_INJECTION_SUSPECTED"


class TimeFrame(str, Enum):
    CURRENT = "CURRENT"
    PAST = "PAST"
    HYPOTHETICAL = "HYPOTHETICAL"


class TargetSubject(str, Enum):
    SELF = "SELF"
    FAMILY_OR_CAREGIVER = "FAMILY_OR_CAREGIVER"
    THIRD_PARTY = "THIRD_PARTY"


class Polarity(str, Enum):
    AFFIRMATIVE = "AFFIRMATIVE"
    NEGATIVE = "NEGATIVE"


class RouterStatus(str, Enum):
    E_EMERGENCY = "E_EMERGENCY"
    U_URGENT_HUMAN = "U_URGENT_HUMAN"
    M_MEDICATION_REFERRAL = "M_MEDICATION_REFERRAL"
    R_POLICY_BOUNDARY = "R_POLICY_BOUNDARY"
    Q_CLARIFICATION = "Q_CLARIFICATION"
    G_GENERAL_EDUCATION = "G_GENERAL_EDUCATION"
    O_OUT_OF_SCOPE = "O_OUT_OF_SCOPE"
    F_ROUTER_DEPENDENCY = "F_ROUTER_DEPENDENCY"


# 只有這個 router_status 可以進入檢索（CONTRACT_v1 §1.1）。
PERMITTED_ROUTER_STATUS = RouterStatus.G_GENERAL_EDUCATION


class RetrievalRoute(str, Enum):
    VECTOR = "VECTOR"
    GRAPH = "GRAPH"
    HYBRID = "HYBRID"


class RetrievalStatus(str, Enum):
    SUCCESS = "SUCCESS"
    EMPTY = "EMPTY"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    CONFLICT = "CONFLICT"
    ERROR = "ERROR"


class GraphPathStatus(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class EvidenceRiskLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class WarningCode(str, Enum):
    ROUTER_STATUS_NOT_PERMITTED = "ROUTER_STATUS_NOT_PERMITTED"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    UNKNOWN_ENUM_VALUE = "UNKNOWN_ENUM_VALUE"
    LOW_CONFIDENCE_EVIDENCE_DROPPED = "LOW_CONFIDENCE_EVIDENCE_DROPPED"
    GRAPH_HOP_LIMIT_REACHED = "GRAPH_HOP_LIMIT_REACHED"
    EMPTY_AFTER_THRESHOLD_FILTER = "EMPTY_AFTER_THRESHOLD_FILTER"
    VOCABULARY_CODE_MISSING = "VOCABULARY_CODE_MISSING"
    SOURCE_NOT_CLINICALLY_REVIEWED = "SOURCE_NOT_CLINICALLY_REVIEWED"
    STALE_SOURCE_DATE = "STALE_SOURCE_DATE"
    POSSIBLE_INJECTION_CONTENT = "POSSIBLE_INJECTION_CONTENT"
    RETRIEVER_DEGRADED = "RETRIEVER_DEGRADED"


class ScoreType(str, Enum):
    SIMILARITY = "similarity"
    RERANK = "rerank"
    GRAPH_TRAVERSAL = "graph_traversal"


class ChunkStatus(str, Enum):
    ACTIVE = "active"
    REVOKED = "revoked"
    SUPERSEDED = "superseded"


class RetrieverType(str, Enum):
    VECTOR = "vector"
    GRAPH = "graph"


class EntityType(str, Enum):
    SUBSTANCE = "Substance"
    CONDITION = "Condition"
    SYMPTOM = "Symptom"
    LAB_PARAMETER = "LabParameter"
    TRIGGER = "Trigger"
    INTERVENTION = "Intervention"


class SubjectType(str, Enum):
    SUBSTANCE = "Substance"
    CONDITION = "Condition"
    TRIGGER = "Trigger"


class ObjectType(str, Enum):
    SUBSTANCE = "Substance"
    CONDITION = "Condition"
    SYMPTOM = "Symptom"
    LAB_PARAMETER = "LabParameter"
    INTERVENTION = "Intervention"


class RelationType(str, Enum):
    CONTRAINDICATED_FOR = "CONTRAINDICATED_FOR"
    CAUTION_FOR = "CAUTION_FOR"
    INDUCES = "INDUCES"
    CAUSES_SIDE_EFFECT = "CAUSES_SIDE_EFFECT"
    REQUIRES_MONITORING = "REQUIRES_MONITORING"
    TREATS = "TREATS"
    INTERACTS_WITH = "INTERACTS_WITH"
    RISK_FACTOR_FOR = "RISK_FACTOR_FOR"
    TRIGGERS = "TRIGGERS"
    IS_A = "IS_A"


class SafetySignalType(str, Enum):
    CONTRAINDICATION = "CONTRAINDICATION"
    CAUTION = "CAUTION"
    SERIOUS_ADVERSE_EVENT = "SERIOUS_ADVERSE_EVENT"
    RISK_FACTOR = "RISK_FACTOR"
    TRIGGER = "TRIGGER"
    INTERACTION = "INTERACTION"
    MONITORING = "MONITORING"
    SIDE_EFFECT = "SIDE_EFFECT"
    GENERAL = "GENERAL"
